name: hyperpay
description: A Flutter plugin to wrap HyperPay SDK for iOS and Android.
version: 0.0.2-alpha
repository: https://github.com/nyartech/hyperpay

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 
  plugin:
    platforms:
      android:
        package: com.nyartech.hyperpay
        pluginClass: HyperpayPlugin
      ios:
        pluginClass: HyperpayPlugin
